name: CI
on: [push]
jobs:
  zig-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          clean: false
      - run: |
          ls -la
          zig test src/tests.zig 
          zig build
